# Generated by Django 4.1.5 on 2023-01-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 1, 4, 15, 23, 49, 607111, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
